spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/database-development-technology?rewriteBatchedStatements=true
    username: root
    password: root
